name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for helping make S.L.U.X become better by raising this issue, we will try to get it solved ASAP
 Regards Tree-T'
        pr-message: 'Thank you for helping make S.L.U.X become better by creating this pull request
 Regards Tree-T'
